# Generated by Django 3.2.9 on 2022-03-08 11:25

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import mptt.fields


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Means',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True)),
                ('description', models.TextField()),
                ('logo', models.ImageField(null=True, upload_to='transport_means/')),
            ],
        ),
        migrations.CreateModel(
            name='RegisteredMeans',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(null=True, upload_to='registered_means/')),
                ('max_weight', models.DecimalField(decimal_places=2, max_digits=5)),
                ('max_volume', models.DecimalField(decimal_places=2, max_digits=5)),
                ('active', models.BooleanField(default=True)),
                ('means', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='registered_means', to='delivery.means')),
                ('owner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='registered_means', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'unique_together': {('owner', 'means')},
            },
        ),
        migrations.CreateModel(
            name='Location',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('lft', models.PositiveIntegerField(editable=False)),
                ('rght', models.PositiveIntegerField(editable=False)),
                ('tree_id', models.PositiveIntegerField(db_index=True, editable=False)),
                ('level', models.PositiveIntegerField(editable=False)),
                ('parent', mptt.fields.TreeForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='children', to='delivery.location')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Destination',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('price', models.DecimalField(decimal_places=2, max_digits=10)),
                ('location_from', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='from_location', to='delivery.location')),
                ('location_to', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='to_location', to='delivery.location')),
                ('means', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='destination', to='delivery.registeredmeans')),
            ],
            options={
                'unique_together': {('means', 'location_from', 'location_to')},
            },
        ),
    ]
