# Generated by Django 3.2.9 on 2022-01-08 16:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('delivery', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='means',
            name='name',
            field=models.CharField(max_length=100, unique=True),
        ),
    ]
