# Generated by Django 3.2.9 on 2021-12-12 14:18

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('delivery', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='DeliveryMeans',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(null=True, upload_to='registered_means/')),
            ],
        ),
        migrations.CreateModel(
            name='Means',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('description', models.TextField()),
                ('logo', models.ImageField(null=True, upload_to='transport_means/')),
                ('rank', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='Destination',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('price', models.DecimalField(decimal_places=2, max_digits=10)),
                ('location', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='destination', to='delivery.location')),
                ('means', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='destination', to='delivery.deliverymeans')),
            ],
        ),
        migrations.AddField(
            model_name='deliverymeans',
            name='means',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='registered_means', to='delivery.means'),
        ),
        migrations.AddField(
            model_name='deliverymeans',
            name='owner',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='registered_means', to=settings.AUTH_USER_MODEL),
        ),
    ]
