# Generated by Django 3.2.9 on 2022-01-08 16:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('delivery', '0002_auto_20220108_1811'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='means',
            name='rank',
        ),
    ]
