# Generated by Django 3.2.9 on 2022-03-11 12:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('delivery', '0002_auto_20220308_1508'),
    ]

    operations = [
        migrations.AlterField(
            model_name='registeredmeans',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='registered_means/'),
        ),
    ]
