# Generated by Django 3.2.9 on 2022-01-09 04:51

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('delivery', '0002_alter_means_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='destination',
            name='location_from',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='from_location', to='delivery.location'),
        ),
    ]
