# Generated by Django 3.2.9 on 2021-12-12 18:19

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('delivery', '0002_auto_20211212_1718'),
    ]

    operations = [
        migrations.AlterField(
            model_name='destination',
            name='location',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='destination_location', to='delivery.location'),
        ),
    ]
