# Generated by Django 3.2.9 on 2021-12-12 18:20

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('delivery', '0003_alter_destination_location'),
    ]

    operations = [
        migrations.AlterField(
            model_name='destination',
            name='location',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='destination', to='delivery.location'),
        ),
    ]
