# Generated by Django 3.2.9 on 2021-12-10 05:40

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import phonenumber_field.modelfields


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Shop',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, unique=True)),
                ('bio', models.TextField()),
                ('created_on', models.DateTimeField(auto_now_add=True)),
                ('logo', models.ImageField(upload_to='store_profiles/')),
                ('pickup_location', models.CharField(max_length=50)),
                ('phone_contact', phonenumber_field.modelfields.PhoneNumberField(max_length=128, region='KE')),
                ('email_contact', models.EmailField(max_length=254)),
                ('owner', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='shops', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
