# Generated by Django 3.2.9 on 2021-12-10 05:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0002_brand_category'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='category',
            name='slug',
        ),
    ]
