# Generated by Django 3.2.9 on 2022-03-11 12:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0003_alter_product_attribute_value'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='attribute_value',
            field=models.ManyToManyField(blank=True, related_name='products', to='store.AttributeValue'),
        ),
    ]
