# Generated by Django 3.2.9 on 2022-03-07 15:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0004_product_active'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='shop',
            name='pickup_location',
        ),
        migrations.RemoveField(
            model_name='shop',
            name='subscription_end_date',
        ),
    ]
