# Generated by Django 3.2.9 on 2021-12-11 05:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0006_auto_20211210_2322'),
    ]

    operations = [
        migrations.AddField(
            model_name='shop',
            name='functional',
            field=models.BooleanField(default=True),
        ),
    ]
