# Generated by Django 3.2.9 on 2021-12-15 06:44

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('order', '0003_auto_20211214_1304'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cart',
            name='owner',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='carts', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='cart',
            name='token',
            field=models.CharField(blank=True, default=uuid.UUID('1aca02e8-389e-4c4c-9c79-d33dc63cad06'), max_length=30, null=True, unique=True),
        ),
    ]
