# Generated by Django 3.2.9 on 2021-12-15 06:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('order', '0004_auto_20211215_0944'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cart',
            name='token',
            field=models.CharField(blank=True, max_length=30, null=True, unique=True),
        ),
    ]
