# Generated by Django 3.2.9 on 2021-12-17 05:35

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('storage', '0002_dailytransit'),
        ('order', '0004_shopdailyorders_storage_location'),
    ]

    operations = [
        migrations.AddField(
            model_name='orderitem',
            name='transit',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='items', to='storage.dailytransit'),
        ),
    ]
