# Generated by Django 3.2.9 on 2021-12-17 06:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('order', '0005_orderitem_transit'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='orderitem',
            name='transit',
        ),
    ]
