# Generated by Django 3.2.9 on 2021-12-17 07:13

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('storage', '0004_dailytransit'),
        ('order', '0006_remove_orderitem_transit'),
    ]

    operations = [
        migrations.AddField(
            model_name='orderitem',
            name='transit',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='items', to='storage.dailytransit'),
        ),
    ]
