# Generated by Django 3.2.9 on 2021-12-15 14:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('order', '0007_alter_cartitem_unique_together'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='token',
            field=models.CharField(blank=True, max_length=20, null=True, unique=True),
        ),
    ]
