# Generated by Django 3.2.9 on 2022-03-05 12:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0003_user_auth_provider'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='role',
            field=models.CharField(choices=[('STAFF', 'staff'), ('STORE_OWNER', 'store_owner'), ('DELIVERY', 'delivery'), ('CUSTOMER', 'customer')], max_length=50),
        ),
    ]
