# Generated by Django 3.2.9 on 2022-03-07 13:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0004_alter_user_role'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='profile',
            name='gender',
        ),
        migrations.DeleteModel(
            name='StaffProfile',
        ),
    ]
