# Generated by Django 3.2.9 on 2021-12-17 05:35

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('delivery', '0005_alter_destination_location'),
        ('storage', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='DailyTransit',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_on', models.DateTimeField(auto_now_add=True)),
                ('arrived_on', models.DateTimeField(null=True)),
                ('delivered', models.BooleanField(default=False)),
                ('end_location', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='end_transit_location', to='storage.storage')),
                ('means', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='delivery.deliverymeans')),
                ('start_location', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='start_transit_location', to='storage.storage')),
            ],
        ),
    ]
