# Generated by Django 3.2.9 on 2021-12-17 06:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('order', '0006_remove_orderitem_transit'),
        ('storage', '0002_dailytransit'),
    ]

    operations = [
        migrations.DeleteModel(
            name='DailyTransit',
        ),
    ]
