# Generated by Django 3.2.9 on 2021-12-17 07:11

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('storage', '0003_delete_dailytransit'),
    ]

    operations = [
        migrations.CreateModel(
            name='DailyTransit',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_on', models.DateTimeField(auto_now_add=True)),
                ('arrived_on', models.DateTimeField(blank=True, null=True)),
                ('delivered', models.BooleanField(default=False)),
                ('end_location', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='transit_end_location', to='storage.storage')),
                ('start_location', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='transit_start_location', to='storage.storage')),
            ],
        ),
    ]
