# Generated by Django 3.2.9 on 2021-12-17 07:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('order', '0007_orderitem_transit'),
        ('delivery', '0005_alter_destination_location'),
        ('storage', '0004_dailytransit'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Storage',
            new_name='StorageFacility',
        ),
    ]
