# Generated by Django 3.2.9 on 2021-12-17 08:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('storage', '0005_rename_storage_storagefacility'),
    ]

    operations = [
        migrations.AlterField(
            model_name='dailytransit',
            name='created_on',
            field=models.DateField(auto_now_add=True),
        ),
    ]
