name: Deploy To Heroku Server

on:
  pull_request:
    branches: [development]

jobs:
  call-workflow:
    uses: Ken-mbira/SHOPS_GALORE/.github/workflows/test.yaml@development
    secrets:
      SECRET_KEY: ${{ secrets.SECRET_KEY }}
      CLOUDINARY_NAME: ${{ secrets.CLOUDINARY_NAME }}
      CLOUDINARY_API_KEY: ${{ secrets.CLOUDINARY_API_KEY }}
      CLOUDINARY_SECRET: ${{ secrets.CLOUDINARY_SECRET }}
      EMAIL_USE_TLS: ${{ secrets.EMAIL_USE_TLS }}
      EMAIL_HOST: ${{ secrets.EMAIL_HOST }}
      EMAIL_PORT: ${{ secrets.EMAIL_PORT }}
      EMAIL_HOST_USER: ${{ secrets.EMAIL_HOST_USER }}
      EMAIL_HOST_PASSWORD: ${{ secrets.EMAIL_HOST_PASSWORD }}
      SOCIAL_PASSWORD: ${{ secrets.SOCIAL_PASSWORD }}
      GOOGLE_CLIENT_ID: ${{ secrets.GOOGLE_CLIENT_ID }}

  deploy:
    needs: call-workflow
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
      - name: Merge with development
        uses: everlytic/branch-merge@1.1.2
        with:
          github_token: ${{ secrets.MY_TOKEN }}
          source_ref: ${{ github.ref }}
          target_branch: "development"
          commit_message_template: "[Automated] Merged {source_ref} into target {target_branch}"

      - uses: actions/checkout@v2
      - name: Merge with master
        uses: everlytic/branch-merge@1.1.2
        with:
          github_token: ${{ github.token }}
          source_ref: "development"
          target_branch: "master"
          commit_message_template: "[Automated] Merged {source_ref} into target {target_branch}"

      - name: Deployment to heroku
        uses: akhileshns/heroku-deploy@v3.4.6
        with:
          heroku_api_key: ${{secrets.HEROKU_API_KEY}}
          heroku_app_name: "maduka-kibao"
          heroku_email: "devmbira@gmail.com"

      - name: Successful Message
        run: echo Successfully Deployed!!
